language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip3 install -e .

# command to run tests
script:
  - ./tests/test_buchi.py
  - ./tests/test_reachability.py
  - ./tests/test_safety.py
  - ./tests/test_strategy.py
  