language: python
python:
  - "3.7"

addons:
  apt:
    packages:
      - graphviz
      - ffmpeg

# command to install dependencies
install:
  - pip3 install jupyter matplotlib ipympl fimdpenv
  - pip3 install -e .

# command to run tests
script:
  - python ./tests/test_buchi.py
  - python ./tests/test_mecs.py
  - python ./tests/test_reachability.py
  - python ./tests/test_safety.py
  - python ./tests/test_strategy.py
  - jupyter nbconvert --execute ./tut/StrategyTypes.ipynb
  
