dist: focal 

language: python
python:
  - "3.7"

addons:
  apt:
    packages:
      - graphviz
      - ffmpeg

# command to install dependencies
install:
  - pip3 install jupyter matplotlib ipympl fimdpenv
  - pip3 install -e .

# Install Spot
before_script:
  - wget -q -O - https://www.lrde.epita.fr/repo/debian.gpg | sudo apt-key add -
  - sudo echo 'deb http://www.lrde.epita.fr/repo/debian/ stable/' >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install spot libspot-dev spot-doc python3-spot

# command to run tests
script:
  - python ./tests/test_buchi.py
  - python ./tests/test_mecs.py
  - python ./tests/test_mincap.py
  - python ./tests/test_reachability.py
  - python ./tests/test_safety.py
  - python ./tests/test_strategy.py
  - python ./tut/StrategyTypes.py
  - jupyter nbconvert --execute ./tut/ProductDBA.ipynb
